# Generated by Django 5.0.4 on 2024-04-06 20:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_hospedes', models.IntegerField()),
                ('quantidade_banheiros', models.IntegerField()),
                ('aceita_animais', models.BooleanField(default=False)),
                ('valor_limpeza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_ativacao', models.DateField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=100)),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cod_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reserva', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.TextField(blank=True)),
                ('numero_hospedes', models.IntegerField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cod_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.anuncio')),
            ],
        ),
    ]
